defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: node:10.15.1

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install APT packages
          command: apt-get update && apt-get install nasm -y
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run:
          name: Install NPM dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Build
          command: BUILD_NUMBER=$CIRCLE_SHA1 npm run build
      - store_artifacts:
          path: ~/repo/build
      - persist_to_workspace:
          root: .
          paths:
            - .babelrc
            - .circleci/
            - build/
            - config/
            - node_modules/
            - scripts/
            - src/
            - tests/
            - Dockerfile
            - package.json
            - tsconfig.json
            - tslint.json
            - package-lock.json
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npm test
  deploy:
    <<: *defaults
    environment:
      - DOCKER_VERSION: 18.06.1~ce~3-0~debian
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Docker
          command: |
            apt-get install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common
            curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
            apt-key fingerprint 0EBFCD88
            add-apt-repository \
              "deb [arch=amd64] https://download.docker.com/linux/debian \
              $(lsb_release -cs) \
              stable"
            apt-get update
            apt-get install -y docker-ce=$DOCKER_VERSION
      - setup_remote_docker
      - deploy:
          name: Deploy
          command: ./.circleci/deploy_to_heroku.sh

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
  build_test_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - test:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - deploy:
          context: heroku_deployment
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
