version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: node:8.9.4
    environment:
      - DOCKER_VERSION: 17.03.1-ce
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            set -x
            curl -L -o /tmp/docker-$DOCKER_VERSION.tgz https://get.docker.com/builds/Linux/x86_64/docker-$DOCKER_VERSION.tgz
            tar -xz -C /tmp -f /tmp/docker-$DOCKER_VERSION.tgz
            mv /tmp/docker/* /usr/bin
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install NPM dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run:
          name: Build
          command: npm run build
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -f dockerfile --rm=false --build-arg NODE_ENV=production --build-arg PUBLIC_PATH=$PUBLIC_PATH -t react-universal-starter-kit:$CIRCLE_SHA1 .
workflows:
  version: 2
  build:
    jobs:
      - build
