defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: node:8.11.3

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install APT packages
          command: apt-get update && apt-get install nasm -y
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "yarn.lock" }}
            - v1-npm-deps-
      - run:
          name: Install NPM dependencies
          command: yarn
      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run:
          name: Build
          command: BUILD_NUMBER=$CIRCLE_SHA1 npm run build
      - store_artifacts:
          path: ~/repo/build
      - persist_to_workspace:
          root: .
          paths:
            - .circleci/
            - build/
            - config/
            - node_modules/
            - scripts/
            - src/
            - Dockerfile
            - package.json
            - tsconfig.json
            - tslint.json
            - yarn.lock
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npm test
  deploy:
    <<: *defaults
    environment:
      - DOCKER_VERSION: 17.03.1-ce
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Docker
          command: |
            set -x
            curl -L -o /tmp/docker-$DOCKER_VERSION.tgz https://get.docker.com/builds/Linux/x86_64/docker-$DOCKER_VERSION.tgz
            tar -xz -C /tmp -f /tmp/docker-$DOCKER_VERSION.tgz
            mv /tmp/docker/* /usr/bin
      - setup_remote_docker
      - deploy:
          name: Deploy
          command: ./.circleci/deploy_to_heroku.sh

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
  build_test_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - test:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - deploy:
          context: heroku_deployment
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
