version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: node:8.9.4-alpine
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install NPM dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -f dockerfile --rm=false --build-arg NODE_ENV=production --build-arg PUBLIC_PATH=$PUBLIC_PATH -t andrewscwei/react-universal-starter-kit:$CIRCLE_SHA1 .
      - run:
          name: Push to Docker Hub
          command: |
            docker push
  test:
    working_directory: ~/app
    docker:
      - image: andrewscwei/react-universal-starter-kit:$CIRCLE_SHA1
    environment:
      - NODE_ENV: test
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install NPM dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run unit tests
          command: npm test
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
