name: CI
on:
  push:
    branches: ["**"]
    tags-ignore: ["v*"]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime:
          - server
          - static
          - edge
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .node-version
      - name: Install Node modules
        run: npm install
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Unit test
        run: npm run test:unit
      - name: Build
        run: npm run build:${{ matrix.runtime }}
      - name: E2E test
        run: npm run test:${{ matrix.runtime }}
  notify:
    name: Notify
    needs: [build]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: andrewscwei/telegram-action@v1
        with:
          success: ${{ needs.build.result == 'success' }}
          cancelled: ${{ needs.build.result == 'cancelled' }}
          bot-token: ${{ secrets.TELEGRAM_DEVOPS_BOT_TOKEN }}
          chat-id: ${{ secrets.TELEGRAM_DEVOPS_CHAT_ID }}
